/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const isLocalhost = Boolean(
  window.location.hostname === "localhost" ||
    // [::1] is the IPv6 localhost address.
    window.location.hostname === "[::1]" ||
    // 127.0.0.1/8 is considered localhost for IPv4.
    window.location.hostname.match(
      /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
    )
);

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:be7e4e95-33c6-4988-8b3c-98c623ccc9ca",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_AgI9xBSrT",
  aws_user_pools_web_client_id: "2sf8accatmnurlo72uths7ccje",
  oauth: {
    domain: "biocare-alpha.auth.us-east-2.amazoncognito.com",
    scope: [
      "aws.cognito.signin.user.admin",
      "email",
      "openid",
      "phone",
      "profile",
    ],
    redirectSignIn: "http://localhost:3001/login/",
    redirectSignOut: "http://localhost:3001/login/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_mobile_analytics_app_id: "8b02414e21e544df8a2d64bbad893ec6",
  aws_mobile_analytics_app_region: "us-east-1",
  aws_user_files_s3_bucket: "bioheart-user-files62455-alpha",
  aws_user_files_s3_bucket_region: "us-east-2",
};

export default awsmobile;
