/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// import {openURLInApp} from './src/services/amplify';

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id:
    'us-east-2:f8c49f59-acfc-4b22-863f-46492cd69b4f',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_AGz5aEqPd',
  aws_user_pools_web_client_id: '1e9bsps3fcil66sbfd225flkg5',
  oauth: {
    domain: 'btcy-acc-delta.auth.us-east-2.amazoncognito.com',
    scope: [
      'aws.cognito.signin.user.admin',
      'email',
      'openid',
      'phone',
      'profile',
    ],
    redirectSignIn: 'http://localhost:3001/login/',
    redirectSignOut: 'http://localhost:3001/login/',
    responseType: 'code',
    options: {
      // urlOpener: openURLInApp,
    },
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: ['FACEBOOK', 'GOOGLE', 'APPLE'],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_mobile_analytics_app_id: '34cb8c7165b442f4ad46a2969867b0ae',
  aws_mobile_analytics_app_region: 'us-east-1',
  aws_user_files_s3_bucket: 'bioheart-user-files162946-delta',
  aws_user_files_s3_bucket_region: 'us-east-2',
  aws_cognito_login_mechanisms: ['PREFERRED_USERNAME'],
};

export default awsmobile;